#!/sbin/openrc-run
# Copyright 2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="universalmediaserver daemon"
description="universalmediaserver daemon"
command="/usr/bin/universalmediaserver"
command_args="console"
pidfile="${PMS_PIDFILE:-/var/run/ums.pid}"
retry="10"
start_stop_daemon_args="
	--background
	--make-pidfile
	${UMS_USER:+--user} ${UMS_USER}
	${UMS_GROUP:+--group} ${UMS_GROUP}
"
depend() {
	need net
}
